# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5c7548bea1ac52b1f785f1a68c8ccd76b54c83fbdf3b9681388b536fd37b5da08db1de1aed3c62820352ec382a3802ae2f1e8ac85dfcb8bd0654135422df3443

test:
  secret_key_base: 8280666790cc5d31a115d6de5bfbf41bb24d145d865b59bbeb80c7cc288fcd3e098345d19071c74a4a6ee2439d929e37cd368f78d581c2e7068b8a9de6eb799f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
